packit/dashboard

main.py, templates/projects.html
This is just a proof of concept - to show that we have such data.
=> Show all/successful projects

.dockerignore, .gitignore
Added `.vscode` in the `.gitignore` and  `.dockerignore`.
`.vscode`  is an auto generated folder by `Visual Studio Code` which store the `settings` for the  `current project`.
This is indeed a very minor modification or maybe not even a  relevant pull  request. I am really new to contributing on open source projects :(
=> added ignoring of .vscode  folder

Makefile
```bash
$ rpm -ql python3-flask | grep bin
/usr/bin/flask-3
/usr/bin/flask-3.7
```
=> [Makefile] python3-flask has no flask binary

Dockerfile, packit_dashboard/app.py
templates copied to docker image
=> template not found issue fixed

Makefile
=> Added support for apt pakage manager

.pre-commit-config.yaml
copied pre config file from github.com/packit-service
*updated by @lachmanfrantisek:*
- Fixes: #12
=> Pre commit configuration file

.zuul.yaml
#13 noop job added as referenced - [https://github.com/packit-service/research/tree/master/zuul](https://github.com/packit-service/research/tree/master/zuul)
=> Creating .zuul.yaml with noop job

packit_dashboard/about/routes.py, packit_dashboard/about/utils.py, packit_dashboard/app.py, packit_dashboard/builds/routes.py, packit_dashboard/config.py, packit_dashboard/home/routes.py, packit_dashboard/packagewide_utils.py, packit_dashboard/projects/routes.py, packit_dashboard/projects/utils.py, templates/main_frame.html
So before I start working on #21 we need a proper project structure. We can't just keep adding code to one python file. So I used flask blueprints to split the app into blueprints (which are also subpackages).
=> Modularize project with flask blueprints

.pre-commit-config.yaml, .zuul.yaml, files/tasks/zuul-project-setup.yaml, files/zuul-pre-commit.yaml
#13 Adding pre-commit to zuul as did in other repos.
=> Adding pre-commit job to Zuul 

.gitignore, .zuul.yaml, Dockerfile.tests, Makefile, files/ansible/install-deps.yaml, files/ansible/recipe-tests.yaml, files/zuul-install-requirements.yaml, files/zuul-tests.yaml, packit_dashboard/packagewide_utils.py, packit_dashboard/projects/utils.py, tests/spellbook.py, tests/tests_requre/__init__.py, tests/tests_requre/test_data/test_requre/tests.tests_requre.test_requre.TestUtilsUsingRequre.test_all_from.yaml, tests/tests_requre/test_data/test_requre/tests.tests_requre.test_requre.TestUtilsUsingRequre.test_return_json.yaml, tests/tests_requre/test_requre.py
=> Add unit tests, make a dockerfile for running tests, and modify makefile to run them.

CONTRIBUTING.md, DCO
Resolves #29 
Took reference from contributing.md of the packit-service.
I've skipped the running packit software locally section as it already covered by #31 . Let me know if it is still needed here.
=> Added contributing guidelines

CONTRIBUTING.md, files/cfg/httpd_packit.conf
Changed configuration to use wildcard certificates.
=> Changed configuration to use wildcard certificates.

frontend/components/projects.js, packit_dashboard/api/routes.py
Temporary fix because #49 will take longer to complete
=> Replace hardcoded URL with env var API URL

.github/stale.yml
Signed-off-by: Frantisek Lachman <flachman@redhat.com>
=> Correct stalebot message

frontend/components/projects_list.js
=> Ignore projects without any handled item

frontend/components/chroot_status.js, frontend/components/koji_builds_table.js, frontend/components/project_info.js, frontend/components/results_copr.js, frontend/components/results_koji.js, frontend/components/results_srpm.js, frontend/components/results_tf.js, frontend/components/srpm_builds_table.js, frontend/components/status_label.js, frontend/components/tf_results_table.js, frontend/components/trigger_link.js, frontend/routes.js
=> Results page

frontend/components/results_srpm.js
=> Show SRPM link only if present

.github/workflows/build-and-push.yml
=> Build using Ubuntu 18.04

Makefile, frontend/components/copr_builds_table.js, frontend/components/tf_results_table.js
**Do not merge before packit/packit-service#1040**
=> COPR builds improvements

frontend/src/components/results_copr.js
=> Do not display instructions for failed COPR builds

frontend/src/components/results_tf.js
=> Make the URL of Testing Farm results more visible

frontend/src/components/pipelines.js, frontend/src/routes.js
---
We consider [Pipelines view](https://dashboard.packit.dev/pipelines) on dashboard to be ready for production use. We're planning to improve the user experience when using pipelines with easier navigation and filtering options.
=> End pipelines' beta phase

frontend/src/components/tables/srpm.js
=> SRPM Builds: remove Results column

frontend/src/components/tables/copr.js, frontend/src/components/tables/koji.js
See the individual commits.
---
N/A
=> Update 2 column names

Dockerfile.tests
=> Update the test image to Fedora Linux 35

frontend/src/components/app_layout.js, frontend/src/components/dashboard.js
=> Blog posts improvements

.pre-commit-config.yaml, files/ansible/install-deps.yaml, frontend/package.json, frontend/src/components/tables/usage.js, frontend/src/components/usage.js, frontend/src/routes.js, frontend/yarn.lock, packit_dashboard/api/routes.py
Fixes #193 
I would be really glad if someone more knowledgeable about React (=any experience is better than mine..;) can take a look and patiently review the code..;)
For the purpose of caching and easier work with dates, I am proxying the API calls through the backend which results in an issue with CORS. I hope using a flask-cors extension for that is fine.
Sadly, monthly and yearly data can't be accessed from prod for now..;(
---
There is a new subpage on our dashboard you can visit to check how much is Packit used.
---
Here is a screenshot with the data from prod instance:
=> Usage page

frontend/src/components/tables/usage.js
This is a fix to really access backend when getting data from backend's API (=flask).
=> Use correct backend URL when fetching usage data

frontend/package.json, frontend/src/components/tables/usage.js
This should work well when deployed but I can't make it work locally..;(
Any suggestion is really welcome!
=> Usage page backend url fix 2

packit_dashboard/api/routes.py
to prevent cross-site scripting vulnerability
=> Sanitize user-provided values

frontend/src/app/Results/ResultsPageKoji.tsx
a quick workaround until packit/packit-service#2082 is resolved.
=> Don't show Koji build logs URL

frontend/src/app/AppLayout/AppLayout.tsx
Follow the Image Builder style of showing info about the source code.
=> Provide a popover about Open Source Services

Makefile, packit_dashboard/api/routes.py, packit_dashboard/app.py
https://github.com/packit/dashboard/security/code-scanning
=> Fix more CodeQL warnings

frontend/src/app/StatusLabel/StatusLabel.tsx
should have been added in 14dd263071
=> Import missing ExclamationTriangleIcon

frontend/src/app/routes.tsx
Add label for Usage menu so that it shows up
FIxes: #269
=> Add label for Usage menu

frontend/src/app/Projects/BranchList.tsx, frontend/src/app/Projects/PullRequestList.tsx
=> Make branchnames and pr ids into links

frontend/src/app/Projects/BranchList.tsx, frontend/src/app/Projects/PullRequestList.tsx, frontend/src/app/Results/ResultsPageCopr.tsx, frontend/src/app/Trigger/TriggerLink.tsx, frontend/src/app/utils/forgeUrls.tsx
They are already part of the gitRepo string.
=> Don't pass repo namespace & name into getXYZLink()

frontend/src/app/Projects/ProjectSearch.tsx
=> Allow to paste an URL into Projects Search

frontend/src/app/Projects/BranchList.tsx, frontend/src/app/Projects/IssuesList.tsx, frontend/src/app/Projects/PullRequestList.tsx, frontend/src/app/Projects/ReleasesList.tsx
=> Add links to Issues and Releases

Dockerfile, files/ansible/install-deps.yaml
Related to packit/deployment#410
=> Use CentOS Stream9 as a base image

frontend/src/app/Results/ResultsPageSyncReleaseRuns.tsx
Now has a show line numbers toggle, wrap test toggle, download and fullscreen button. As well as a scroll to bottom footer button
TODO:
Fixes #332
Related to
---
CC @xsuchy
Improve UX of log search
=> feat: improve log viewer with extra functionality

.pre-commit-config.yaml, frontend/src/app/Usage/UsageList.tsx, frontend/tsconfig.json
Fixes packit/packit-service#2304
Merge after packit/packit-service#2330
=> Add goal Q1 2024 to usage/total charts

frontend/src/app/Usage/UsageInterval.tsx, frontend/src/app/Usage/UsageList.tsx
Related to #374
---
We have fixed crashing of Usage page in case of unsuccessful queries.
=> Check response status for usage queries

frontend/yarn.lock
Our caniuse-lite was outdated and should be updated semi-regularly to
ensure that the builds are accurate to what we want.
TODO:
Fixes
Related to
---
Update browserslist
=> chore: update browserslist

Makefile, frontend/src/app/Results/ResultsPageCoprDetails.tsx
Fixes https://github.com/packit/packit-service/issues/2195.
=> Fix rendering of a "dead" link

frontend/src/app/Results/ResultsPageSyncReleaseRuns.tsx
Adds the step pipeline we use in Copr Builds to Sync Release runs
TODO:
Fixes
Related to
Add step timeline for sync release results
=> feat(UX): Step timeline for Sync Release results

frontend/src/app/Results/ResultsPageSRPM.tsx
Adds the step pipeline we use in Copr Builds to SRPM Builds page as well
TODO:
Fixes
Related to
Add step timeline for SRPM build status
=> feat(UX): Step timeline for SRPM build status

frontend/src/app/Results/ResultsPageKoji.tsx
Adds the step pipeline we use in Copr Builds to Koji Builds page as well
TODO:
Fixes
Related to
Add step timeline for Koji build status
=> feat(UX): Step timeline for Koji build status

frontend/src/app/Dashboard/Dashboard.tsx
We have Page defined in the AppLayout already, so we can remove it from here
TODO:
Fixes
Related to
Improve accessibility by removing nested pages
=> fix: remove extra page

frontend/vite.config.ts
See
https://sharp.pixelplumbing.com/install#vite
TODO:
Fixes
Related to
Exclude image optimization dependency from Vite
=> fix: exclude sharp dependency in Vite config

.dockerignore, Dockerfile, files/ansible/icons.yaml
This adds pnpm files to the project directory within the container so that everything can be built correctly
This also removes the incorrectly set .dockerignore with lock files
=> Updated Dockerfile with pnpm info

frontend/src/components/copr/CoprBuildDetail.tsx, frontend/src/components/koji/KojiBuild.tsx, frontend/src/components/shared/LabelLink.tsx, frontend/src/components/srpm/SRPMBuild.tsx
There were some incorrect stylings here and there that are now fixed.
In particular relating to horizontal divider inconsistencies and label
links.
Enforce consistent styling across pages
=> fix: style improvements to PF components

frontend/src/components/copr/CoprBuild.tsx
This splits the packages up in easier chunks for installation.
Fixes #470
Improve Copr installation instructions
=> feat(Copr): Improved installation instructions

Dockerfile, Dockerfile.tests, files/ansible/install-deps.yaml
Related to packit/deployment#638
=> ci: switch to Fedora-based image
