.gitignore

Add dependencies to git ignore so that they won't be tracked by git. Not sure if it is a relevant change, but I felt it is good to have :)

Chore: add node modules to gitignore

---

package.json
packit_dashboard/app.py
templates/main_frame.html
templates/projects.html

- Replaced the raw object in the projects tab with a list. 
- I also ran black on the entire repo so some code was reformatted.
- Replaced the hardcoded word "information" (which was shown in every tab) with respective headers for each tab.

Display a list of projects instead of the raw python object

---

frontend/components/copr_builds_table.js

Make the table on the Copr builds tab more compact by inlining the chroot labels and display 20 jobs by default.

Copr build tweaks

---

.zuul.yaml

When zuul configuration is stored in the repository, defining 'project.name' is optional.

Guess project name from the repository name

---

files/cfg/httpd_packit.conf

This way it might be possible to lower the memory limit from 200MiB to
128MiB, which could save us 144MiB calculated across all projects.
Taken from packit/packit-service#596.

Optimize httpd memory usage

---

frontend/components/koji_builds_table.js

Earlier, the tooltip displayed the chroot which was already mentioned in the label. Meanwhile the status was only reflected by the color.
This is how it looked:
Now the tooltip shows the status.

Rectify koji builds status tooltip text

---

frontend/components/status.js

we received feedback from @martinpitt that saying we are healthy is
confusing when builds are failing
therefore we'll instead inform that status page is about API healthiness
and not about builds

status: update text and say "Packit API"

---

.github/workflows/build-and-push.yml

This reverts commit 5fa6cc6884dd1ec633c13be7058c44d755c8ff40.
Should be fixed in buildah-build v2.4

Revert "Build using Ubuntu 18.04"

---

frontend/components/results_tf.js

In case the state of testing farm run is `new`, the URL is not
provided and we displayed clickable link with no URL.
Fixes #94

Fix URL for Testing Farm if not provided

---

files/ansible/recipe.yaml

Forgot to add the install node modules task in ansible. A step in the Containerfile copies the entire frontend folder so I didnt encounter this locally as it copied my node_modules.
Fixes https://github.com/packit/dashboard/actions/runs/842199459
~~(I'm checking image build on a clean git clone now, wait afew minutes)~~ Checked. It's working fine

Fix buildah image build

---

frontend/src/components/tables/pipelines.js

Fixes #139
---
Dashboard no longer shrinks Copr/Koji icons when being open in narrow view.

Fix shrinking of Copr/Koji icons

---

frontend/src/components/results/copr.js
frontend/src/components/results/koji.js
frontend/src/components/results/srpm.js
frontend/src/components/results/testing_farm.js
frontend/src/components/tables/copr.js
frontend/src/components/tables/koji.js
frontend/src/components/tables/pipelines.js
frontend/src/components/tables/srpm.js
frontend/src/components/tables/testing_farm.js
frontend/src/utils/time.js

Merge with packit/packit-service#1223
---
Dashboard now shows more readable format of time, e.g. _just now_, _a minute ago_, etc. If you wish to see exact date-time of the run, you can either hover over the time and tooltip with details appear. In case of result pages more readable format is present in the tooltip rather than by default. Also times are now shown in your local time zone.
For tables: ![](https://i.imgur.com/pP0qh6c.png)
For results: ![](https://i.imgur.com/ibQx27p.png)

Datetime improvements

---

frontend/src/components/app_layout.js

Fixes #126
---
Clicking on logo on dashboard no longer opens a new page, but rather reloads the current one.

Do not open new tab from logo

---

frontend/src/components/tables/pipelines.js

Merge after packit/packit-service#1282 to check whether it displays it correctly with that change (it should split current one pipeline into separate).

Update pipelines view for tests without build

---

Makefile
frontend/src/components/results/srpm.js

Merge before: packit/packit-service#1315
---
N/A

SRPM Build result page: display info when log is missing

---

frontend/src/components/results/srpm.js
frontend/src/components/tables/pipelines.js
frontend/src/components/tables/srpm.js
frontend/src/components/trigger_info.js

SRPMBuildModel in packit-service was updated, it has now status attribute instead
of success and additional Copr related attributes, these changes are reflected into
packit-service API and the info we process in dashboard, therefore the views
need to be updated to show correct status and new info.
Related to packit/packit-service#1324
For SRPMs built by us we will show also start and finished time:
For SRPMs built in Copr there are additional links:
---

Update views to reflect SRPM changes related to building in Copr

---

frontend/src/components/results/srpm.js

Since there is an issue with wrapping and overlap of line numbers with
actual logs, disable the line numbers till it's fixed on the side of
patternfly's log viewer.
Fixes #166
- since we have low traffic on the dashboard repo, let's try conventional commits here
- will create some pre-commit check for it in separate commit
Issue with displaying of SRPM logs on dashboard has been fixed by disabling the line numbers until it's fixed on the side of the React framework we are using.

fix(srpm): disable line numbers in logs

---

.github/PULL_REQUEST_TEMPLATE.md
Dockerfile
files/ansible/install-deps.yaml

We do that also in [files/ansible/recipe.yaml](https://github.com/packit/dashboard/blob/main/files/ansible/recipe.yaml#L18) so this was probably copy-pasta left-over ?
After [bumping the base image to F35](https://github.com/packit/deployment/pull/306) it results in
```
npm ERR! enoent ENOENT: no such file or directory, open '/src/package.json'
```
@csomh I hope we will not need the same change you did in packit/packit-service#1363 also here. I see the similar pattern in [run_httpd.sh](https://github.com/packit/dashboard/blob/main/files/scripts/run_httpd.sh), [httpd_packit.conf](https://github.com/packit/dashboard/blob/main/files/cfg/httpd_packit.conf), [install-deps.yaml](https://github.com/packit/dashboard/blob/main/files/ansible/install-deps.yaml#L15)

Don't run npm install when installing dependencies

---

frontend/src/components/jobs.js
frontend/src/components/results/propose_downstream.js
frontend/src/components/status_labels.js
frontend/src/components/tables/propose_downstream.js
frontend/src/components/trigger_link.js
frontend/src/routes.js
frontend/src/utils/forge_urls.js
packit_dashboard/api/routes.py
tests/data/propose-downstream_result_issue_trigger.json
tests/data/propose-downstream_result_pr_trigger.json
tests/data/propose-downstream_result_release_trigger.json
tests/data/propose-downstream_table.json

I also added fake data for propose-downstream job because dashboard-stg can't see propose-downstream jobs at all and I guess we will be developing the `Propose Downstream` part in dashboard in future. 
Current solution how to "insert" the fake data to dashboard-stg is really bad :grinning:  You need to pass this json file to corresponding `jsonToRow` function. e.g. [here](https://github.com/packit/dashboard/blob/main/frontend/src/components/tables/copr.js#L66)
Propose downstream demo:
https://user-images.githubusercontent.com/70757578/157068611-10614fbe-e7af-44d3-a548-24527fe95ec8.mov
Successfully submitted target demo:
https://user-images.githubusercontent.com/70757578/157068651-fa16f24a-bb17-44fd-8b49-7bff045ab9ab.mov
Running target:
Fixes #155 
Merge after …

View for propose-downstream

---

.pre-commit-config.yaml
frontend/src/components/tables/pipelines.js

Preview:
---
Dashboard now shows also `propose-downstream` jobs in pipelines view. We have also merged all jobs to one column to minimize dead space on the page.

Propose downstream pipelines

---

files/ansible/install-deps.yaml

Remove yet another nss_wrapper and install nodejs instead of npm, which
was replaced by yarn.
Leftover from #181.

Fix dashboard dependencies

---

README.md

Fix the path to the Packit logo in README.md

---

files/scripts/run_httpd.sh

The server name in prod has no instance slug.

Fix the server name in prod

---

frontend/src/components/jobs.js

When loading data for the jobs table, do not load all data at once, but
only once the specific tab is being open.
This prevents the issue with getting time out on the API endpoint.
Fixes #186
Fixes PACKIT-2484
---

fix(jobs): load data lazily

---

frontend/src/components/results/testing_farm.js

In packit/packit-service#1658 there was implemented that a TF run can be triggered with multiple Copr builds and API for TF runs changed (copr_build_id -> copr_build_ids) as well. This PR implements displaying those builds correctly in the TF result view.
Related to packit/packit-service#1658
The view for the TF runs with only one build stays the same and this is how it looks like for TF runs with more builds:
---
N/A

Display multiple Copr builds for TF results if present

---

.github/workflows/build-and-push.yml

Related to packit/deployment#396
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

Use environment files instead of set-output command

---

files/scripts/run_httpd.sh

```
$ mod_wsgi-express-3 start-server --help
--https-only          Flag indicating whether any requests made using a HTTP
request over the non secure connection should be
redirected automatically to use a HTTPS request over
the secure connection.
--hsts-policy PARAMS  Specify the HSTS policy that should be applied when
HTTPS only connections are being enforced.
```
https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html
Enterprise Security Standard (ESSv9) requirement.

Enforce HTTPS with HSTS

---

Dockerfile
files/ansible/install-deps.yaml
files/ansible/recipe.yaml

In order to be able to upgrade the base image to Fedora Linux 36,
we need Node.js 18 and use --openssl-legacy-provider. Otherwise
'yarn run build' fails due to crypto issues.
Merge after #181 and after the base image was upgraded to Fedora Linux 36 and rebuilt.

Update the Node.js-stack to enable upgrading to F36

---

frontend/src/components/results/testing_farm.js

When receiving TF results from Packit API endpoint, ignore ‹null›s as Copr build, so that we don't have a link to Copr build consisting of ‹null›.
Fixes #198
---
We have fixed a bug in dashboard that linked `null` as a Copr build for Testing Farm runs that do not require any Copr build.

fix(results,tf): ignore ‹null›s as Copr builds

---

.gitignore
frontend/src/components/forge.js
frontend/src/components/namespace.js
frontend/src/components/project_info.js
frontend/src/components/results/copr.js
frontend/src/components/results/koji.js
frontend/src/components/results/propose_downstream.js
frontend/src/components/results/srpm.js
frontend/src/components/results/testing_farm.js

When we merged the refactor and updating of dependencies the way that
routes are handled changed as well due to major version upgrade for
React router. This has now been fixed by using useParams() instead of
props component parameter
closes #204
TODO:
Fixes
Related to
---
Fix router parameters no longer working after updating dependencies

fix: router params

---

frontend/package.json
frontend/src/components/app_layout.js
frontend/src/components/branch.js
frontend/src/components/forge.js
frontend/src/components/issues.js
frontend/src/components/namespace.js
frontend/src/components/pr.js
frontend/src/components/project_info.js
frontend/src/components/projects_list.js
frontend/src/components/releases.js
frontend/src/components/results/copr.js
frontend/src/components/results/koji.js
frontend/src/components/results/propose_downstream.js
frontend/src/components/results/srpm.js
frontend/src/components/results/testing_farm.js
frontend/src/components/tables/copr.js
frontend/src/components/tables/koji.js
frontend/src/components/tables/pipelines.js
frontend/src/components/tables/propose_downstream.js
frontend/src/components/tables/srpm.js
frontend/src/components/tables/testing_farm.js
frontend/src/components/trigger_info.js
frontend/src/components/trigger_link.js
frontend/src/utils/forge_urls.js
frontend/src/utils/time.js

The linter had a lot of warnings when starting up the dev server. This
fixes all those warnings and makes sure we do things correctly
- Array.map() was changed to Array.forEach() as it was only iterating and
not changing
- Initial render call had explicit ignore added to clarify that it's a
one-time render thing
- Unused imports and functions removed
- Incorrect usage of useState was fixed for columns (never needed
state management for it)
- checkValidProject was changed to be a callback and the useState
using it was changed to correctly use it as a dependency
TODO:
Note that #205 fixes some things for me, so until that is merged I cannot properly verify that the changes work as it should
Fixes
Related to
---
Fix ESLint warnings

refactor: fix eslint issues

---

frontend/.prettierignore
frontend/package.json
frontend/public/index.html
frontend/yarn.lock

Using prettier helps with ensuring consistency between everyone (and
also prevents having to rely on pre-commit to fix everything for you)
With this you should be able to run `yarn run prettier` and also
configure your editor/IDE to use the right settings as well.
I noticed there was already settings in `package.json` for Prettier, but
no file existed for ignoring artifact folders like build
TODO:
Fixes
Related to
Merge before
#205
---
Add opinionated code formatter Prettier as a dependency

chore: add Prettier as dependency

---

Makefile
frontend/package.json
frontend/src/app.js
frontend/src/components/forge_icon.js
frontend/src/components/tables/copr.js
frontend/src/components/tables/koji.js
frontend/src/components/tables/pipelines.js
frontend/src/components/tables/propose_downstream.js
frontend/src/components/tables/srpm.js
frontend/src/components/tables/testing_farm.js
frontend/yarn.lock

This starts using React Query for utilizing requests to the Packit API.
If the user is on a page and alt tabs currently or is inactive for a
while the page will refresh the content automatically as well. This can
be disabled either for each query individually or modified globally.
With React Query we also use caching to a better extent if it is ever
needed.
When the demo loads pages 1 through 3 it is due to alt tabbing to showcase the refresh of pages
TODO:
https://user-images.githubusercontent.com/6598829/216692107-8fb0c5ca-000c-41f2-8ee9-84a052a65dd8.mp4
Fixes #212 #211 #210
Related to
---
Improve fetching of API content in paginated tables

feat: load indicator using React Query

---

frontend/src/components/dashboard.js
frontend/src/components/projects_list.js
frontend/src/components/status_labels.js
frontend/src/components/tables/copr.js
frontend/src/components/tables/koji.js
frontend/src/components/tables/pipelines.js
frontend/src/components/tables/propose_downstream.js
frontend/src/components/tables/srpm.js
frontend/src/components/tables/testing_farm.js

This adds more information to the dashboard for screen readers. It also changes the description of the various tables as the screen readers already read out the word table
Fixes #217
Related to
---
Improve accessibility for tables and its content

feat: accessibility improvements

---

frontend/src/app.js
frontend/src/components/app_layout.js
frontend/src/components/jobs.js
frontend/src/components/project_info.js
frontend/src/components/status_labels.js
frontend/src/components/tables/pipelines.js
frontend/src/routes.js

This fixes a bunch of different things. Specifically the issues I opened today
Most of the links within the site now default to using React Router Link or NavLink where appropriate, preventing any page reload. Fixes #221
There is now a way to see current page on the sidebar if you are on pipelines or jobs page for instance. Fixes #222
Jobs tables have been updated to allow linking to specific tables. I also took the liberty of refactoring the website route structure to now fully utilize Outlet instead of rendering components wherever needed and having to deal with other issues like the tables would have been. Fixes #223
TODO:
Fixes
Related to
---
Refactor React Router to use Outlet for routes
Add links for job tables

Refactor React Router usage

---

frontend/src/components/results/srpm.js

The link is required for the StatusLabel. Use the Copr web URL (we do the same for Copr build results).
Fixes #229
---
￼

Set link for the SRPM results status label

---

frontend/src/components/status_labels.js

In some situations, the StatusLabel is initialized with a null link ( e.g. when the propose-downstream fails, the link should point to the downstream PR, but there is no), which could previously lead to rendering errors.
Related to #229 
---
￼

Allow null link in StatusLabel

---

frontend/src/components/branch.js
frontend/src/components/error_app.js
frontend/src/components/error_connection.js
frontend/src/components/issues.js
frontend/src/components/pr.js
frontend/src/components/project_info.js
frontend/src/components/projects_list.js
frontend/src/components/releases.js
frontend/src/components/results/copr.js
frontend/src/components/results/koji.js
frontend/src/components/results/srpm.js
frontend/src/components/results/sync_release.js
frontend/src/components/results/testing_farm.js
frontend/src/components/tables/copr.js
frontend/src/components/tables/koji.js
frontend/src/components/tables/pipelines.js
frontend/src/components/tables/srpm.js
frontend/src/components/tables/sync_release.js
frontend/src/components/tables/testing_farm.js
frontend/src/components/tables/usage.js
frontend/src/routes.js

If the app crashes we casn now have a error element that can display to the user. This will display a log of what happened, and also let the user know they can report it upstream and also go back to the main page.
First commit shows the feature
Second commit shows refactor of existing connection error 
App crash exception
Refactor of connection issue error
TODO:
Fixes #234 
Related to
---
Add user friendly interface if dashboard crashes

feat: Catch app crashes

---

.github/workflows/build-and-push.yml
Dockerfile
Makefile
frontend/public/index.html
frontend/src/app/AppLayout/AppLayout.js

Within the header there will now be a shorthash visible that links to packit/dashboard page
Part of #209
TODO:
Fixes
Related to
---
Add commit hash for dashboard in page header

feat: add commit hash in page header

---

Makefile

There's a small typo
TODO:
Fixes
Related to
---
Fix typo in Makefile for React

fix typo in Makefile arg

---

frontend/src/app/StatusLabel/BaseStatusLabel.tsx

This happened when the URL was null and we tried to use `startsWith` on it. For this to be fixed we have to assert that it is not null and proceed with the assumption that it can be null.
Specifically, this happens when propose downstrean doesn't have the `downstream_pr_url` attribute set.
TODO:
Fixes
#254
Related to
---
Fix propose downstream detailed view from crashing when downstream URL is null

fix: propose downstream crashed the application

---

Dockerfile
Makefile
files/scripts/run_httpd.sh

I don't know how you guys run the dashboard locally, but I expected to try it in a container.
However the `README` suggests installing dependencies directly on the machine and running it there.
This is what I had to do to make 'make run-container-stg' work as (I) expected.

Make 'make run-container-stg' work as expected

---

.github/workflows/build-and-push.yml

In 67650a1, they have been put on one line, this doesn't work according to the documentation… and has already bitten me once before.
Revert this change and split them to multiple separate lines.

fix(gha): build args »need« to be on separate lines

---

frontend/src/app/Projects/ProjectSearch.tsx
frontend/src/app/Projects/Projects.tsx
frontend/src/app/Projects/ProjectsList.tsx

We were using cards for the list itself, together with no differentiator
for each project, such as their icon, it made it very difficult to
browse in an easy way.
This change moves it over to a composable Table which we can use in
a future change to automatically fetch the branches, releases, and
issues for each project without leaving the page.
However, the table itself offers more information and gives less
confusion as to what each entry is and where to look to see the name --
the repository name will always be on the left side now, which it
didn't before
TODO:
Fixes
Related to
---
Our dashboard now shows projects in a table instead of the cards.

feat: change projects from cards to table

---

.gitignore

Added in 519a111, removed during the rebase as a possible mistake.

chore: add mockServiceWorker back to gitignore

---

frontend/src/app/utils/forgeUrls.tsx

Will come in handy during the workshop

Add getCommitLink() to return URL to the specified commit

---

files/ansible/common.yaml
files/ansible/install-deps.yaml
files/ansible/recipe.yaml

F37 already contains `nodejs` 18 and I haven't seen any build problems.
C9S (#258) contains `nodejs` 16 but everything looks OK as well.
Fixes #247
Reverts 3cd34b74
@mfocko do you have any idea why @csomh started deleting the `/src/frontend/node_modules` in the 3cd34b74 and whether I should revert it too? I left it untouched (i.e. we still delete it) and it looks OK.

Don't install nodejs:18 (RPM) module

---

frontend/src/app/Results/ResultsPageTestingFarm.tsx

Add a link on the Testing Farm Results page to the actual web_url for Testing Farm.
Fixes #276 
This is from the Contribute to an Open Source Service workshop at Devconf 2023.

Turn Pipeline ID into link to Testing Farm results

---

frontend/src/app/Results/ResultsPageCopr.tsx
frontend/src/app/Results/ResultsPageKoji.tsx

For Copr builds and Koji builds, we link the SRPM build result as SRPM
logs, which is misleading and should be changed to be consistent with
how we link Copr build results from Testing Farm results.
Fixes #263

Be consistent on the status for Copr and Koji builds

---

frontend/src/app/Results/ResultsPageCopr.tsx
frontend/src/app/Trigger/TriggerLink.tsx
frontend/src/app/utils/forgeUrls.tsx

This refactors the usage off all `forgeUrls` and makes sure every entry has a link (by assuming they're hosting a GitLab instance)
TODO:
Fixes #261
Related to
---
￼

feat: change link triggers to show URL

---

frontend/src/app/AppLayout/AppLayout.tsx

The about open source popover had an issue where it would show up in
the wrong location, causing issues when it comes to opening it sometimes.
We can fix this by forcing the popover to assume `bottom-end` flip behavior
TODO:
Fixes
Related to
---
Fix popover resizing dashboard incorrectly

fix: popover showing up in wrong place

---

frontend/src/app/AppLayout/AppLayout.tsx

This changes the page header to use Masthead instead of the
legacy PageHeader component. This simplifies the structure of
the header as well as allowing us to do more things in the future
TODO:
Fixes
Related to
---
Refactor page header away from legacy components

refactor: Move page header away from legacy

---

frontend/src/app/utils/forgeUrls.tsx

Example: The `rpms/gpxsee#35` link in https://dashboard.stg.packit.dev/results/pull-from-upstream/662

Fix URLs for Pagure

---

files/ansible/install-deps.yaml
files/scripts/run_httpd.sh
packit_dashboard/api/routes.py
packit_dashboard/app.py
packit_dashboard/utils.py

https://github.com/wntrblm/flask-talisman#talisman-http-security-headers-for-flask
Related to packit/private#28

Use Talisman to set HTTP security headers

---

Makefile
files/architecture-red.svg
packit_dashboard/api/routes.py
tests/unit/test_views.py

This is to be able to generate an SVG file with architecture with the URLs using actual, deployed git hashes.

Generate architecture SVG via API

---

files/architecture-red.svg

https://github.com/packit/dashboard/f660d97/stable -> https://github.com/packit/dashboard/tree/f660d97

Fix the link in architecture SVG

---

.github/workflows/preview-pr.yml

* Expose the tokens only to the steps where the tokens are required.
* Do not merge the script used for notifications on the PRs.

Harden automated build

---

frontend/src/app/Jobs/Jobs.tsx
frontend/src/app/routes.tsx

Rename it to 'Upstream Koji Builds' to make it clear these are not the production ones triggered in downstream.
---
N/A

Rename Koji Builds tab

---

frontend/src/app/Results/ResultsPageCopr.tsx

Adjust how we include the epoch in the build result page. We get the value in packit-service from Copr API and the behaviour there recently changed: https://github.com/fedora-copr/copr/pull/2876
---
N/A

Adjust Copr build epoch handling for None

---

frontend/src/app/Usage/Usage.tsx
frontend/src/app/Usage/UsageInterval.tsx
packit_dashboard/api/routes.py

This PR adds a new group of charts showing the usage trends.
The implementation follows the same workflow as with the existing usage charts:
* The data for the charts are collected, processed and cached on the backend.
* Frontend loads the data from the backend API.
The implementation can be improved a lot but I am worried I would never propose it otherwise..;)
Ideally, the usage queries should be moved to service and optimised. It takes a while to load it but it's probably fine since regular people don't check it on a daily basis. And if someone needs the data, the delay is not an issue.
The parameters for each view can be tweaked but this is what I would start with:
* Past year (= weekly for the last 52 weeks)
* Past month (= daily for the last 30 days)
* Past week (= daily for the last …

Usage trend charts

---

frontend/src/app/Usage/UsageInterval.tsx
packit_dashboard/api/routes.py

This adds two new charts to show the usage of jobs for the number of unique projects.
Two new charts are available at https://dashboard.packit.dev/usage to show the trends based on the number of active projects.

Add usage trend charts for project count

---

files/ansible/recipe.yaml

From the yarn docs:
> Yarn will not install any package listed in `devDependencies` if the
> `NODE_ENV` environment variable is set to `production`. Use this flag
> to instruct Yarn to ignore `NODE_ENV` and take its production-or-not
> status from this flag instead.
This should ensure that no development dependencies, such as `surge`, are installed at all in the image that we use for deployments.
Yet another follow-up to the vulnerability report for the MP+ deployment.

chore: install yarn deps in production mode

---

frontend/src/app/Usage/Usage.tsx
frontend/src/app/Usage/UsageList.tsx
packit_dashboard/api/routes.py

Trends are not so relevant here and too demanding on resources.

Add tab with the total usage numbers

---

frontend/src/app/Projects/ProjectsList.tsx
frontend/src/app/routes.tsx

The underlying `ProjectsList` component didn't take care of namespaces or forges so just fixing that fixed the issue
There was also a trailing forwardslash in the routing which was incorrect
TODO:
Fixes
#321
Related to
---
Fix projects with forge and with/without namespace not showing right results

fix: projects not fetching right API

---

frontend/src/app/Results/ResultsPageCopr.tsx
frontend/src/app/Results/ResultsPageCoprDetails.tsx
frontend/src/app/Results/ResultsPageKoji.tsx
frontend/src/app/Results/ResultsPageSRPM.tsx
frontend/src/app/Results/ResultsPageSyncReleaseRuns.tsx
frontend/src/app/Results/ResultsPageTestingFarm.tsx
frontend/src/app/utils/SHACopy.tsx

This unifies the results to a better UX that should make it less confusing
while also having a consistent layout between different builds and runs
This idea is a change from table to a [description list](https://www.patternfly.org/v4/components/description-list)
Before and after for testing farm
Before and after for Copr builds
TODO:
Fixes 
#288
#262
Related to
---
Improve UX of results page

feat: Consistent results pages

---

frontend/src/app/AppLayout/AppLayout.tsx
frontend/src/app/routes.tsx

This will prepare us for more granular interaction with project selection in the future. For now until that is implemented we have this to go with.
TODO:
Fixes
Related to
#306 
---
Move sidebar routes around and categorize them

refactor: Move sidebar items around

---

frontend/src/app/Trigger/TriggerInfo.tsx

Before this change it opened the link in a new page/tab but did not
show the URL it is going to, so you could not copy the link or see that
it is a link
TODO:
Fixes
Related to
---
Show the external links correctly in project view

fix: External link in TriggerInfo to show link

---

frontend/src/app/Projects/ProjectsList.tsx

Within the Projects view the rows when in a small viewport does not
display the correct labels. This is now corrected
Before:
After:
TODO:
Fixes
Related to
---
Address incorrect label and label format in Projects view

fix: correct labels for Projects in small viewport

---

frontend/src/app/Results/ResultsPageCoprDetails.tsx
frontend/src/app/utils/LabelLink.tsx

Within Copr Build results there is an SRPM Build link that is within the website. To make it seamless with loading we should use NavLink. This changes that
TODO:
Fixes
Related to
---
Improve SRPM link within Copr Build results

feat: Router link for SRPM build link

---

frontend/src/app/Projects/ReleasesList.tsx

Currently ReleasesList uses the PatternFly classes for the table but not
the table itself. This changes it to use the PF component
TODO:
Fixes
Related to
---
Change releases table in Project details to use PatternFly table

fix: ReleasesList to use PatternFly table

---

frontend/src/app/Projects/ProjectSearch.tsx

onChange now takes 2 arguments, see https://www.patternfly.org/components/forms/text-input/#textinput
---
We have fixed the issue with dashboard Projects search.

Fix onChange for TextInput objects

---

frontend/src/app/Jobs/Jobs.tsx
frontend/src/app/Jobs/KojiBuildsTable.tsx
frontend/src/app/Results/ResultsPageKoji.tsx
frontend/src/app/routes.tsx

Create a separate table for downstream Koji builds and adjust the result view to the API changes.
Fixes #214
---
Downstream Koji builds are now shown in a separate table in `/jobs/downstream-koji-builds`.

Show downstream Koji builds

---

frontend/src/app/Results/ResultsPageSyncReleaseRuns.tsx

There was a leftover comment that should have been uncommented
TODO:
Fixes
Related to
---
Fix logs not utilizing the whole height in fullscreen mode

fix: fullscreen logs not using the whole height

---

frontend/src/app/Jobs/Jobs.tsx

Ignore table contents from image as I have other files changed locally
TODO:
Fixes
Related to
---
Improve UX of Job tabs by detaching from tables

refactor: detach page nav from content

---

frontend/src/app/Usage/UsageInterval.tsx
packit_dashboard/api/routes.py

* Add info about onboarded projects to the backend API.
* Add new cumulative usage charts to show the state of onboarding.
* Show the newly onboarded projects. Both globally or once the project starts to use a new job.
Fixes: packit/packit-service#2232
Some screenshots using prod data:
---
There are new usage charts at https://dashboard.packit.dev/usage showing the status of new projects' onboarding.

Onboarding charts

---

frontend/src/app/Usage/UsageList.tsx
packit_dashboard/api/routes.py

* Show the number of active projects in usage charts instead of the legend for the top project that started to be less important and hard to fit into the page.
* Remove chart of all projects since it's independent to the time span.
* Add a progress chart for the Packit's 2023/Q4 goal.
Screenshot using stage data:
---
The usage page at https://dashboard.packit.dev/usage newly shows the number of active projects and the progress of Packit's goal to have 200 projects using release syncing by the end of the year 2023.

Packit usage charts simplification and packit goal

---

packit_dashboard/app.py

Yes… I've really obliterated it in the previous PR.

fix: don't import non-existing endpoint

---

frontend/src/app/Jobs/BodhiUpdatesTable.tsx
frontend/src/app/Jobs/Jobs.tsx
frontend/src/app/Pipelines/PipelinesTable.tsx
frontend/src/app/Results/ResultsPageBodhiUpdate.tsx
frontend/src/app/routes.tsx
frontend/tsconfig.json

Fixes #215
Merge after packit/packit-service#2311
Preview with fake data without triggers:
---
Packit dashboard now shows information about Bodhi updates.

Show Bodhi updates in jobs and pipelines

---

frontend/src/app/Jobs/BodhiUpdatesTable.tsx
frontend/src/app/Jobs/CoprBuildsTable.tsx
frontend/src/app/Jobs/KojiBuildsTable.tsx
frontend/src/app/Jobs/SRPMBuildsTable.tsx
frontend/src/app/Jobs/SyncReleaseStatuses.tsx
frontend/src/app/Jobs/TestingFarmResultsTable.tsx
frontend/src/app/Results/ResultsPageBodhiUpdate.tsx
frontend/src/app/Results/ResultsPageCopr.tsx
frontend/src/app/Results/ResultsPageKoji.tsx
frontend/src/app/Results/ResultsPageSRPM.tsx
frontend/src/app/Results/ResultsPageSyncReleaseRuns.tsx
frontend/src/app/Results/ResultsPageTestingFarm.tsx
frontend/src/app/Trigger/TriggerLink.tsx

This splits the linking from the text in the TriggerLink component
so that it now can be used in a more versatile way, such as setting
internal Packit dashboard links with the display of TriggerLink.
As UX is going to be more refined in the future, this also helps pay the
way of changing external links to be more uniform without having to
change the TriggerLink once again.
For what is being worked on at the moment with getting Pipeline details
this change would be most welcome when it comes to linking internally
but having the text from TriggerLink.
Related
#377 
TODO:
Fixes
Related to
---
Split TriggerLink into two components to make UX improvements easier

refactor(TriggerLink): Split link and text

---

frontend/package.json
frontend/src/app/Results/ResultProgressStep.tsx
frontend/src/app/Results/ResultsPageCoprDetails.tsx
frontend/src/app/utils/Timestamp.tsx
frontend/yarn.lock

Introduces a step timeline functionality in place of the existing text fields. Visually it will at a glance give a more holistic view at a glance without removing any of the necessary detail one might want.
Throughout the whole stage, the change will indicate when something started and when it ended. Visually in time-relative means with detailed timedate variant on hover using Tooltips
This should be seen as an MVP as it currently lacks relative information such as build status and links to the different steps. In the future, this can be adapted to other results pages.
TODO:
Fixes
Related to
UX improvement for Copr build timeline

feat(UX): Step timeline for Copr build status

---

frontend/src/app/Pipelines/PipelinesTable.tsx

We migrated TriggerLink to use the term trigger instead of build to be
more accurate. With that change we also split the text and link to be
separate, which we didn't address in the PipelinesTable either
TODO:
Fixes
Related to
Fix pipelines showing e is undefined

fix: PipelinesTable incorrectly using TriggerLink

---

frontend/src/app/Jobs/Jobs.tsx

Whenever you went to the Jobs page from the sidebar, you could click jobs again and it didn't redirect you to the copr-builds anymore.
This meant that the page would display no tabs selected and there would be no content below the tabs, such as the Copr Builds table. To fix this we had to fix the `useEffect` to include `matches` which has the URL information. That way whenever the URL changes this will also change
To make it even nicer on the eyes, we will hard-import Copr Builds table so that it will be visible if the url is just `/jobs` again and it didn't redirect correctly. This also makes it so that the rendering of the table won't flicker if you click Jobs in the sidebar over and over. Note that the statuses for the table will still flicker, as it loads the table again and the …

fix: Redirect jobs page better

---

frontend/src/app/Results/ResultProgressStep.tsx

Some dependencies to `useMemo` in ResultProgressStep wasn't updated and
didn't render properly. This should have been caught by linting when
this was being implemented. The linting should be fixed by #392
TODO:
Fixes
Related to
Fix memoize dependencies in `ResultProgressStep`

fix: memoize dependencies in `ResultProgressStep`

---

frontend/package.json
frontend/tsconfig.json

This changes the default tabbing to be 2 spaces instead of the current
4 spaces.
tsconfig.json is also changed to add missing commas
TODO:
Fixes
Related to
---
￼

Change Prettier formatter tabbing from 4 to 2

---

CONTRIBUTING.md
README.md

GitHub has apparently changed syntax for no good reason…
Related to https://fosstodon.org/@FrostyX/112552088714938785

docs: fix the alerts in markdown

---

.github/workflows/build-and-push.yml
Dockerfile

Followup of #410
I would like to avoid writing the secret into a file, but the `buildah` version in the action doesn't support env vars. Therefore open to any suggestions and opening it as draft :pray:

Expose SENTRY_AUTH_TOKEN for frontend build

---

frontend/package.json

When we do production builds we use --production, which skips the
devDependencies completely. Moving `@sentry/vite-plugin` to dependencies
will fix this issue
TODO:
Fixes
Related to
N/A

fix: move Sentry dependency from dev to prod

---

frontend/src/app/Results/ResultProgressStep.tsx
frontend/src/app/Results/ResultsPageCoprDetails.tsx
frontend/src/app/Results/ResultsPageKoji.tsx
frontend/src/app/Results/ResultsPageSRPM.tsx
frontend/src/app/Results/ResultsPageSyncReleaseRuns.tsx

This changes the existing work on `ResultProgressStep` to include
status handling for cancelled and failed. Further improving UX by
ensuring that the status reporting is consistent across the page
Fixes
Improve UX for task progression results 

feat: Extend progress stepper results

---

CONTRIBUTING.md

We were recommending using 1024 that doesn't work anymore as it is not allowed with mod_wsgi
TODO:
Fixes
Related to
Increase local certificate generation from 1024 to 2048 for development

chore: increase RSA size in CONTRIBUTING.md

---

files/ansible/install-deps.yaml
files/scripts/run_httpd.sh
packit_dashboard/app.py

With this change we now have mod_http2 installed and enabled. Local testing indicates that HTTP/2 works as intended as seen below
```
❯ curl https://dashboard.localhost:8443/ --insecure --head
HTTP/2 200
content-length: 1564
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
content-security-policy: default-src 'self' *.packit.dev; object-src 'none'; style-src 'unsafe-inline' 'self'
strict-transport-security: max-age=31536000;includeSubDomains
referrer-policy: strict-origin-when-cross-origin
content-type: text/html; charset=utf-8
date: Mon, 24 Jun 2024 15:41:03 GMT
server: Apache
```
TODO:
Fixes
Related to
Enable HTTP/2 for Packit dashboard

chore: Enable HTTP/2 protocol for dashboard

---

frontend/package.json
frontend/tsconfig.json
frontend/vite.config.ts
frontend/yarn.lock

We have the images already in the source code but we do not minimize
depending on where we use them. This takes care of that
We also now split the JS files a bit to improve fetching, but it is not
a performance improvement as they all will still load at the same time
TODO:
Fixes
Related to
Automatically reduce image size on build

perf: Minimize images as they are used in the app

---

frontend/package.json
frontend/src/App.tsx
frontend/src/app/Pipelines/PipelineDetail.tsx
frontend/src/app/Pipelines/PipelinesTable.tsx
frontend/src/app/routes.tsx
frontend/yarn.lock

Commit message to be changed, still in draft.
Results so far
TODO:
Fixes
Related to
Introduce detail page for individual pipelines

feat: Pipeline detail view

---

frontend/eslint.config.mjs
frontend/package.json
frontend/src/app/AppLayout/AppLayout.tsx
frontend/yarn.lock

With ESLint 9 being out and plugins slowly migrating, this takes care of
the migration of ESLint config from package.json to its own
eslint.config.mjs. This is needed as package.json and .eslintrc is
deprecated
TODO:
Fixes
Related to
Upgrade ESLint config structure

chore: upgrade ESLint to use new flat config

---

frontend/src/app/Results/ResultsPageCopr.tsx

`dnf` is in EL since EL8, `yum` there is just a compatibility wrapper. Also the subsequent steps don't consider `yum` at all.
Just get rid of it.

Fix Copr build installation instructions

---

frontend/src/app/Results/ResultsPageBodhiUpdate.tsx

This will show a space separated list, but perhaps having a NVR per line would be better? If so, I welcome any tips how to do that with PatternFly :slightly_smiling_face: 
Related to https://github.com/packit/packit-service/issues/2379.
Merge after https://github.com/packit/packit-service/pull/2475.

Show multiple NVRs on Bodhi update result page

---

frontend/src/components/srpm/SRPMBuild.tsx

This makes the build log always visible as it will always return from
packit. Otherwise users would not get any logs when an SRPM build has
failed, meaning they would have to chase it down through the link
Takes up on results from #371
TODO:
Fixes
Related to
Always show SRPM Build logs

fix: Always show build log link for SRPM

---

frontend/src/components/srpm/SRPMBuild.tsx

In a previous PR I removed the parenthesis as part of the refactor
without noticing. This commit adds it back
Fix Build logs and Results for SRPM builds not being in parenthesis

fix: add parenthesis back to SRPM Build log links

---

files/ansible/recipe.yaml

With the new restructure to use workspaces with pnpm we need to run the install within the workspace itself rather than in /frontend. We need the workspace as biome CI will work better when we have the pnpm packages in the project root
Fix builds failing due to incorrect folder

fix: builds failing due to pnpm

---

.github/workflows/preview-pr.yml

This sets the nodejs version from lts to 20 as
lts itself needs to be more specific
Fix PR preview for dashboard

fix: preview PR with set NodeJS version

---

frontend/src/components/statusLabels/StatusLabel.tsx

New colors and icons for:
* running
* pending
* skipped
Fixes #460
TODO:
Fixes
Related to
Previously the pending status had same color and icon as skipped status.
Now we added the icons and colors for those two statuses, that are different from each other, and this had changed also for the running state.

Add missing states to status labels

---

.github/workflows/preview-pr.yml

We forgot to install pnpm inside the deploy PR workflow which caused it to always fail. With this we should now install pnpm v9
Install pnpm in deploy PR preview workflow

chore: Install pnpm in preview PR workflow

---

frontend/package.json
frontend/src/components/copr/CoprBuild.tsx
frontend/src/routeTree.gen.ts

This improves the installation instructions to align better with
installing the specific build we're displaying. If not for this you
couldn't install rhel9 specific chroots as dnf copr would assume epel9
Fixes #470
Add chroot to Copr build installation instructions

fix(Copr): Add chroot to copr enable

---

frontend/src/apiDefinitions.ts
frontend/src/components/jobs/Jobs.tsx
frontend/src/components/osh/OSHScan.tsx
frontend/src/components/osh/OSHScansTable.tsx
frontend/src/components/statusLabels/StatusLabel.tsx
frontend/src/queries/osh/oshScan.ts
frontend/src/queries/osh/oshScanQuery.ts
frontend/src/queries/osh/oshScans.ts
frontend/src/queries/osh/oshScansQuery.ts
frontend/src/routeTree.gen.ts
frontend/src/routes/jobs/osh-scans.tsx
frontend/src/routes/jobs_/osh-scans.$id.tsx

Related to #441 
Dashboard now provides views for OpenScanHub scans.

Introduce views for OpenScanHub

---

frontend/src/components/statusLabels/StatusLabel.tsx
frontend/src/components/testing-farm/CoprDataListItem.tsx

This adds more information while also taking away some extra steps
relating to the Copr builds associated with the testing farm results.
Now looks like this
Improve UX of Copr builds in Testing Farm runs

feat: More build info in Testing Farm runs

---

frontend/src/apiDefinitions.ts
frontend/src/components/jobs/Jobs.tsx
frontend/src/components/osh/OSHScan.tsx
frontend/src/components/osh/OSHScansTable.tsx
frontend/src/routeTree.gen.ts
frontend/src/routes/jobs/openscanhub.tsx
frontend/src/routes/jobs_/openscanhub.$id.tsx

There were some stuff missing regarding styling of the API and what went
on within components. In particular a lot of additions that were not
changed after copying from another component.
As for the API interfaces they were missing the submitted_time which
showed errors within the components themselves.
Also URLs and titles have been renamed to indicate OpenScanHub more
explicitly as we do not have to use abbreviations.
Rename OpenScanHub URLs and improved styling

Improve OpenScanHub URLs & ensured TypeScript compliance

---

frontend/src/main.css
frontend/src/main.tsx
frontend/src/routes/__root.tsx

Introduce a footer with the external links from the sidebar as they
mixed in-app and external links. Also added GitHub links to Dashboard
and Service.
Added footer to dashboard

feat: Introduce a footer

---

.github/workflows/preview-pr.yml

With the removal of an unused pnpm-lock with workspaces the workflow started to fail as it doesn't use the newer file location.
Fixed PR preview yet again

chore: Update pnpm cache location

---

frontend/src/apiDefinitions.ts
frontend/src/components/copr/CoprBuild.tsx

The API definition did not take `null` for `built_packages` and thus never showed an issue with the code. This change fixes both the type and the issue itself.
Fixes #491 
Fix Copr page crashing due to `built_packages` being `null`

fix(Copr): Handle `built_packages` being null

---

frontend/src/apiDefinitions.ts
frontend/src/components/jobs/Jobs.tsx
frontend/src/components/koji/KojiTagRequest.tsx
frontend/src/components/koji/KojiTagRequestsTable.tsx
frontend/src/queries/koji/kojiTagRequest.ts
frontend/src/queries/koji/kojiTagRequestQuery.ts
frontend/src/queries/koji/kojiTagRequests.ts
frontend/src/queries/koji/kojiTagRequestsQuery.ts
frontend/src/routeTree.gen.ts
frontend/src/routes/jobs/koji-tag-requests.tsx
frontend/src/routes/jobs_/koji-tag-request.$id.tsx

Related to https://github.com/packit/packit-service/issues/2576.
Merge after https://github.com/packit/packit-service/pull/2648.

Add Koji tagging requests

---

frontend/src/apiDefinitions.ts
frontend/src/queries/osh/oshScan.ts
frontend/src/queries/osh/oshScans.ts

Follow-up of packit/packit-service#2655

Adjust code to OSH API endpoint rename

---

frontend/src/apiDefinitions.ts
frontend/src/components/osh/OSHScan.tsx
frontend/src/components/statusLabels/StatusLabel.tsx

There was a discrepancy between what the API should return and what is
being returned. This fixes some of the fields that can be null and
handles the case where that occurs.
Related to https://dashboard.packit.dev/jobs/openscanhub/3694
Update Packit's OpenScanHub API endpoint schema

Fix OpenScanHub schema not reflecting API data

---

packit_dashboard/api/routes.py
packit_dashboard/app.py

Fixes packit/packit-service#2529

fix(api): deny all API requests

---

files/scripts/run_httpd.sh

Fixes packit/packit-service#2529

fix(wsgi): alias the API server name

---

frontend/src/components/bodhi/BodhiUpdatesTable.tsx
frontend/src/components/copr/CoprBuildsTable.tsx
frontend/src/components/koji/KojiBuildsTable.tsx
frontend/src/components/koji/KojiTagRequestsTable.tsx
frontend/src/components/osh/OSHScansTable.tsx
frontend/src/components/srpm/SRPMBuildsTable.tsx
frontend/src/components/sync-release/SyncReleasesTable.tsx
frontend/src/components/testing-farm/TestingFarmRunsTable.tsx

This changes the screen reader usage in table header cells to use the
prop instead of the classname itself for consistency and potential CSS
issues.

Table: Screen reader usage for header cells

---

frontend/src/components/projects/ProjectSearch.tsx

This commit should fix the problem when searching for projects by pressing Enter, doesn't work.
You can now search projects on our dashboard by pressing Enter. 🕵️ 

fix(project-search): make search button of type submit
